apiVersion: apps/v1
kind: Deployment
metadata:
  name: dating-deployment
spec:
  selector:
    matchLabels:
      app: dating-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dating-app
    spec:
      containers:
      - name: dating-container
        image: shoebweb007/dating:7
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
